server:
  port: 8777
#  context-path: /api


spring:
    datasource:
        name: test
        url: jdbc:mysql://192.168.1.87:3306/ssm?useUnicode=true&characterEncoding=utf8
        username: root
        password: root@2017
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    jpa:
      hibernate:
        ddl-auto: update

    mail:
      host: smtp.ym.163.com
      username: chenyalan@andlinks.com
      password: chenyalan
      default-encoding: UTF-8

#        #thymeleaf模板解析器
    thymeleaf:
      mode: HTML5
      encoding: UTF-8
      content-type: text/html
      cache: false

    redis:
      database: 6
      host: 192.168.1.22
      port: 6379
      password:
      pool:
        max-active: 8 #连接池最大连接数，使用负值表示没有限制
        max-wait: -1  #最大阻塞等待时间,使用负值表示没有限制
        max-idle:  8 #连接池中的最大空闲连接
        min-idle: 0  #连接池中的最小空闲连接
      timeout: 0  #连接超时时间（毫秒）



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.andlinks.mybatis.entity




#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


#属性
mail:
   from: chenyalan@andlinks.com

redis:
   time: 3600

user:
   photo:
       address: /root/qqch/user/

isdevmode: false
